apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: prod
  
  #annotations: 
    # service.beta.kubernetes.io/aws-load-balancer-type: "External"
spec:
  #type: LoadBalancer
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
    protocol: TCP
