apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: prod
  
  annotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
